services:
  flask:
    restart: unless-stopped
    build:
      context: ./flask
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - PINECONE_API
      - LANGCHAIN_TRACING_V2
      - LANGCHAIN_ENDPOINT
      - LANGCHAIN_PROJECT
      - LANGCHAIN_API_KEY
      - GROQ_API_KEY
      - TAVILY_API_KEY
      - HF_TOKEN
    deploy:
      resources:
        reservations:
          cpus: "1.0"
          memory: 4G
    ports:
      - mode: ingress
        target: 5000
        published: 5000
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys, urllib.request; urllib.request.urlopen(sys.argv[1]).read()", "http://localhost:5000/health"]
